"use client"
import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { useState } from 'react'


const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
const [darkmode, setDarkmode] = useState()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`min-h-screen ${darkmode ?'bg-zinc-900':'bg-zinc-100'}`}>
        <Navbar darkmode={darkmode} setDarkmode={setDarkmode} />
        <div className='flex'>
        
        <div className={`mt-24 w-screen `}>{children}</div>
        </div>
        <Footer/>
        </div>
       
        </body>
    </html>
  )
}
